// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckNetIsolation():Promise<boolean>;

export function Connect(arg1:string):Promise<Error>;

export function ProxyingInfo():Promise<main.ProxyInfo>;

export function Terminate():Promise<void>;
