// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ProxyingInfo() {
  return window['go']['main']['App']['ProxyingInfo']();
}

export function Terminate() {
  return window['go']['main']['App']['Terminate']();
}
